### ISSUE TITLE
XML 1.0 EBNF

### ISSUE THREAD

**Issue by robjens** [Engelberg/instaparse#100]
Hi,

XML 1.0 EBNF, as found [here](http://www.jelks.nu/xml/xmlebnf.txt) line 3 contains:

```
Char ::= #x9 | #xA | #xD | [#x20-#xD7FF] | [#xE000-#xFFFD] | [#x10000-#x10FFFF]
S ::= (#x20 | #x9 | #xD | #xA)+
```

My LT chokes on it, I take instaparse doesn't consume those character literal tokens, as in, I don't see them anywhere in the intro/readme. The only place I recall seeing them in ABNF, in Instaparse that is, but here they claim that form is EBNF. It isn't that common to use them there? or some other reason those are left out? Not sure yet how portable the rest is to instaparse :abnf but I guess there is only one way to find out :P

Thanks

**Comment by Engelberg** [comment]
Right, those character literal tokens are not part of any official EBNF spec I've ever seen.  ABNF has something similar, using % rather than #.  The other peculiar thing about this grammar is that it uses regular expressions in places without really making clear that's what they are, for example: `([a-z] | [A-Z])`.

You could probably make this work by converting the tokens explicitly over to strings and regexes, e.g.,

"\u0009" 
#"[\\u0020-\\uD7FF]"
#"[0-9]

**Comment by robjens** [comment]
Thanks for the prompt reply, glad to learn, as those things/questions are notoriously hard to Google :+1:
