### ISSUE TITLE
hash-map as output format

### ISSUE THREAD

**Issue by carocad** [Engelberg/instaparse#109]
First of all Engelberg, Thanks for such an amazing piece of software :)
I would like to know if you have considered supporting hash-map as output format. I know that both the enlive and hiccup format represent accurately the sort of tree structure that you want to show, nevertheless for tree traversing I (personally) find both format to be a bit verbose and not so clear in the way that the traversing must be written.

Take as an example your example on the "Output format" section on your README:
```
=> (as-and-bs-enlive "aaaaabbbaaaabb")
{:tag :S,
 :content
 ({:tag :AB,
   :content
   ({:tag :A, :content ("a" "a" "a" "a" "a")}
    {:tag :B, :content ("b" "b" "b")})}
  {:tag :AB,
   :content
   ({:tag :A, :content ("a" "a" "a" "a")}
    {:tag :B, :content ("b" "b")})})}
```
Traversing it would require checking the content of the :tag element and then if it matches get the value inside the :content. So for example to get the value of the :A tag inside the first AB I would do something like this (please correct me if I'm wrong):
```
(->> (as-and-bs-enlive "aaaaabbbaaaabb")
        (:content)
        (first)
        (:content)
        (first)
        (:content))
```
I avoid checking if the tag matches to not write so much in this post. From my point of view this code (data) doesnt say too much about what I want to achieve. I am proposing that the output format may be something like this:
```
{:S,
 ({:AB 
    ({:A ("a" "a" "a" "a" "a")}
     {:B ("b" "b" "b")})}
  {:AB
    ({:A ("a" "a" "a" "a")}
     {:B ("b" "b")})})}
```
So that something like this would be possible:
```
(->> (as-and-bs-enlive "aaaaabbbaaaabb")
        (:S)
        (first)
        (:AB)
        (first)
        (:A))
```
I think that it is way more clear that I want to extract the first A in the first AB of my S-tart rule. In the case that the keyword dont match I just get a nil as result, but in the enlive format I may get a return value which is doesnt match the S-AB-A if I would have more options to choose from and if these could match a given pattern.

**Comment by Engelberg** [comment]
That's an interesting idea.  I hadn't ever considered it because you're really just using maps here as an ordered pair (your maps never have more than one key, they are just grouping a single key with a value).  So conceptually, `{:A ["a" "a" "a"]}` is little different from `(cons :A ["a" "a" "a"])` which is simply `'(:A "a" "a" "a")`.

I see your point that the map representation makes it slightly easier to delve down looking for a specific part of the data structure.  (The downside is that retrieving the tag and the content are a little more complex, i.e., `(key (first ...))` and `(val (first ...))`.

It's fairly easy to write a short helper function to achieve what you want with the existing formats, something like:

```clojure
(defn get-contents-ensuring-tag [tag data]
   (when (= (:tag data) tag) (:contents data))
```

resulting in 

```clojure
(->> (as-and-bs-enlive "aaaaabbbaaaabb")
        (get-contents-ensuring-tag :S)
        (first)
        (get-contents-ensuring-tag :AB)
        (first)
        (get-contents-ensuring-tag :A))
```

You can pick a shorter name, of course.

I think this solution is sufficiently easy that I'm reluctant to take on the complexity of adding and documenting another output format.

**Comment by carocad** [comment]
Well I still think that using a hash-map would make it very easy to traverse the map assuming of course that there is a specific tag combination that you are looking for. In my case though I discovered that it was not completely necessary to reach a specific combination but rather to traverse the complete map, for which clojure already has quite some functions.

Nevertheless as I was learning to traverse the trees I was having quite some troubles since the clojure documentation is not always so clear. I was wondering if you could put a little reference to a tutorial that you consider appropriate for doing that?

**Comment by Engelberg** [comment]
If you really want to get skilled at processing trees in Clojure, I
recommend this textbook, which uses Racket, a very similar language to
Clojure:
http://www.ccs.neu.edu/home/matthias/HtDP2e/part_four.html#%28part._sec~3abtrees%29
