### ISSUE TITLE
Printing issue with parse errors on carriage returns 

### ISSUE THREAD

**Issue by zmaril** [Engelberg/instaparse#117]
There seems to be a difference in how carriage returns and newlines are being printed out in error messages. The below is a small test case: 

```clojure
(ns scratch.scratch
  (:require [instaparse.core :as insta]))

(def carriage-grammar
  "statement = (token '\\r')*
   token     = 'A' | 'B' ")
(def newline-grammar
  "statement = (token '\\n')*
   token     = 'A' | 'B' ")

(def newline-parse  (insta/parser newline-grammar))
(def carriage-parse (insta/parser carriage-grammar))

(def good-error (newline-parse  "A\nC\n"))
(def odd-error  (carriage-parse "A\rC\r"))
```

On my machine, good error prints as follows: 
```
Parse error at line 2, column 1:
C
^
Expected one of:
"B"
"A"
```

Bad error prints as follows:
```
Parse error at line 1, column 3:
A
  ^
Expected one of:
"B"
"A"
```

It seems like the error printer isn't recognizing carriage returns the same way it is newlines. This has been a confusing issue for me for the past few weeks and I just now realized this was what was causing such strange messages during debugging. As an intermediate step, I've been replacing carriage returns with newlines, but I imagine others, particularly windows users, will run into this sometime.

**Comment by zmaril** [comment]
In fact, I'm going to bet that [this line](https://github.com/Engelberg/instaparse/blob/master/src/instaparse/failure.clj#L12) is causing the problems. I would imagine expanding it to include `\r ` would make the problem go away. Testing locally.

**Comment by aengelberg** [comment]
[Carriage returns](https://en.wikipedia.org/wiki/Carriage_return) (`\r`) occur almost always in conjunction with line-feeds (`\n`), which is why you may often hear the phrase "carriage-return line feed" (CRLF), which is used instead of `\n` on files in Windows.
```clojure
=> (println "ab\rc")
cb
```
A CR by itself is used to reset the head of the printer without changing lines, so I am not surprised that Instaparse behaves weirdly when trying to print a single `\r`.

Usually `'\r'? '\n'` is used in parsers to handle both single line-feeds and CRLFs, allowing both Unix and Windows styles to be parsed. What is your use-case for parsing single carriage-returns in a string?

**Comment by zmaril** [comment]
I'm parsing input from users generated on a machine that uses `\r\space` alone instead of in conjunction with `\n`. I've been told this is a quirk of some Windows programs but I haven't found any good resources as to why this is done. I'll ask around to see what programs they are using to generate the weird line breaks but I don't think I can get them to switch anytime soon.

**Comment by zmaril** [comment]
Seems like the best solution here is to just replace `\r\space` with `\n` and not worry about single carriage returns. I had handled this in the parser code to identify the characters as whitespace but I didn't realize until today that was what was making the error messages be strange. I'll just do a search and replace on the strings beforehand and not worry about this.
