### ISSUE TITLE
Grammar parsing error: Expected one of...

### ISSUE THREAD

**Issue by semaj** [Engelberg/instaparse#122]
Here is my grammar:

~~~clojure
(def to-syntax
  (insta/parser
   "AL = NUM | SYM | FUN | CALL
    NUM = ('0' | '1' | '2' | '3' | '4' | '5' | '6' | '7' | '8' | '9')+
    SYM = ('a' | 'b' | 'c' | 'd' | 'e' | 'f' | 'g' | 'h' | 'i' | 'j' | 'k' | 'l' | 'm' | 'n' | 'o' | 'p' | 'q' | 'r' | 's' | 't' | 'u' | 'v' | 'w' | 'x' | 'y' | 'z' | '+' | '-' | '\\' | '*')+
    FUN = '(' SYM+ ' [' SYM+ '] ' AL ')'"))
~~~

And here is the error that appears when running `lein repl`: 

~~~
#error {
 :cause Error parsing grammar specification:
Parse error at line 4, column 40:
    FUN = '(' SYM+ ' [' SYM+ '] ' AL ')'
                                       ^
Expected one of:
)
|
!
&
ε
eps
EPSILON
epsilon
Epsilon
....
~~~

I've scoured the docs, but I'm sure I'm missing something - what is it?

**Comment by Engelberg** [comment]
I'm unable to test this out myself right now, but looking at it, I'd say the problem is almost certainly the `'\\'`.  This would work fine to denote an escaped backslash character if you were representing the grammar in a separate resource file and slurping it in, but when you put the grammar directly in a Clojure string, you have to double each backslash since Clojure's reader requires each backslash to be escaped before instaparse ever sees the single-quoted string and can do its own escaping.

So try `'\\\\'`.

**Comment by semaj** [comment]
Thanks @Engelberg !
