### ISSUE TITLE
Using instaparse with verbal regex

### ISSUE THREAD

**Issue by Immortalin** [Engelberg/instaparse#124]
Is it possible to integrate instaparse with [Verbal Regular Expressions](https://github.com/VerbalExpressions/ClojureVerbalExpressions)?

**Comment by Engelberg** [comment]
Do Verbal Regular Expressions print as regular expressions at the REPL?  If so, one option is to construct the regex with that library, and then paste the resulting regex into the instaparse DSL.

Otherwise, the best way to integrate it would be to use the instaparse combinators namespace, which lets you use the full power of Clojure to build up your grammar.  `regexp` is the combinator that takes a regular expression, so you'd just pass it the output from Verbal Regular Expressions.
