### ISSUE TITLE
Creating grammars functionally

### ISSUE THREAD

**Issue by thelazydogsback** [Engelberg/instaparse#127]
I'm just getting started, so I hope I'm not missing something...
It would seem most natural to be able to create grammars functionally rather than via strings:
So the example parser would be something like:

    (let [As (insta/oneOrMore (text "a"))  
           Bs (insta/oneOrMore (text "b")) ]
              (insta/zeroOrMore (insta/seq ( [As Bs] )))

The textual ABNF would just be a layer of pre-processing that produced the same tree.
Of course, I could write a wrapper to generate the ABNF from this, but then you need to parse it again to get the intent.  (Obviously this is because the grammar isn't known until run-time.)
Note I don't want to parse with functors (and probably get recursive descent), but create the same parser artifact that you do now to get all the nice behavior of instaparse.

Also, how do I call one parser form another?

thanks

**Comment by Engelberg** [comment]
This section of the README explains how to compose parsers with functions.

Calling one parser from another is then simply a matter of merging their maps.

For example, if parser1 is a map derived from "A = blah blah" then you can create parser2 by using the rule A, i.e., "S = A blah blah"

**Comment by Engelberg** [comment]
Oops, I omitted the link: https://github.com/Engelberg/instaparse#combinators

**Comment by thelazydogsback** [comment]
I apologize for missing that -- that's what I get for trying get the gist of something at 4am when I can't seem to sleep. (When I saw title of the section, I think I immediately thought (naive top-down) "parser combinators" not "parser building combinators".)

Thanks for producing such useful and scalable library -- I've had several attempts at writing parser libs that were supposed to be general and had cool features, but was never able to go that last 20% (which takes 90% of the time...) to get things right.

BTW, can you extrapolate on Clojure's hashing issues that you had to work around? (Or point me to a thread?) Is your work (or something similar) something that needs to be rolled back into clojure core?

thanks

**Comment by Engelberg** [comment]
There were two big hashing issues I needed to contend with:

1. In Clojure, records do not cache their hash values (unlike the other Clojure datatypes, like plain maps).  This is rather frustrating because there has been a patch to address this issue sitting in the JIRA for a couple years now, and it has been "almost included" in the last two releases.  The consequence is that for every data structure, I have to carefully think about whether it is mainly going to be used as a key in a hash map or set (in which case I better use a plain map to represent the data), or whether I am going to be doing a lot of lookups of the components of the data (in which case I should use records which have faster access to their components).  It's annoying to have to constantly weigh that tradeoff for every data structure, and I hope they finally fix this in the next release (Clojurescript, interestingly enough, already does the right thing for records and caches the hash value.

2. The second problem is that Clojure's data structures do not perform "incremental hashing".  What I mean by that is that when you hash [1 2 3], Clojure traverses the whole vector to compute the hash.  If you conj in 4 to produce [1 2 3 4] and then hash it, it traverses the whole vector again (rather than simply computing the new hash value more directly from the hash value of 4 and the hash value of [1 2 3]).  Instaparse is computing the hash over and over again of an ever-growing vector, and if you traverse the whole vector every time, performance slows to a crawl.  So I had to build a version of vectors that recomputes the hash right away, each time an element is added, with a single computation involving the new element and the old vector.

Some other Clojure contributors a while back looked at possibly including this behavior in Clojure, but in the general case it's not entirely clear a) what do do when you put a lazy or infinite sequence into a vector since you can't safely hash that, and b) whether other programs would pay a penalty for immediately computing the hash value of a vector if they don't ever actually end up using the hash value (because they never end up stored as the key in a map or set.

**Comment by Engelberg** [comment]
P.S. I helped evaluate the changing to hashes that occurred in Clojure 1.7, and helped ensure that the new hashing functions would be amenable to instaparse's "incremental hashing" strategy.
