### ISSUE TITLE
Instaparse Performance Issue

### ISSUE THREAD

**Issue by prakhar21** [Engelberg/instaparse#142]
Hey,  @Engelberg
I have written the parser for extracting Noun Phrase and Preposition Phrase from the given sentence.

If, I give input to be of 3 or more lines then the parses takes around 40-50 seconds to parse it. Whereas, input of 1 line takes 3-4 seconds for parsing.

How can I speed up this parsing process, because I need to run it on a lot more example sets, each of 3 lines approximately.

Thanks

**Comment by Engelberg** [comment]
This almost certainly means that your grammar is still ambiguous.

I wrote up some tips here:
https://github.com/Engelberg/instaparse/blob/master/docs/Performance.md

Pay close attention to tips 5-7

**Comment by prakhar21** [comment]
Okay, I get it. But, I am confused on how does it return just one result if we not use (insta/parses).
On what basis, does it shows the result.

**Comment by Engelberg** [comment]
Most likely your problem is that your "anything" rule that picks up the extra stuff includes whitespace characters in the regular expression.  So every time you hit a patch of whitespace, the parser has to consider both the interpretation of the whitespace characters as whitespace, and also the interpretation that is part of the regular expression in your anything rule.  I can't be sure that this is your problem, but this is the kind of thing I see people do all the time that can really bog things down, because you get exponential growth in complexity for every space character in your text.  Try eliminating whitespace characters from your token regexes.

When you use insta/parse, it just returns the first valid parse it finds.  Right now, it processes rules from right-to-left unless you specify ordered choice.  But every branch point is something it needs to record as a potential spot to backtrack to, so even though it is only looking for one parse, ambiguity can hurt performance.
