### ISSUE TITLE
Add option for (insta/visualize) to return binary image data

### ISSUE THREAD

**Issue by dimitrijer** [Engelberg/instaparse#147]
First of all, this library made my life so easier, so thanks Mark and everyone!

It would be very neat for `(insta/visualize)` to return rhizome image rather than writing it to a file or showing it in a window. At the moment I write the image to a temp file, only to load it back in.

Any suggestions? It would make sense to me for this to be default `visualize` behavior. Maybe there could be a wrapper function that did something to the image (write to file, show in new window), and the original function could then return the image.

**Comment by Engelberg** [comment]
Does rhizome support this?  It's been a while since I looked at this, but I seem to remember visualize just being a thin wrapper around rhizome.  So, the next step would be to evaluate what is possible to do with rhizome, I think.

**Comment by dimitrijer** [comment]
As far as I can see, rhizome picks up binary data from `dot` output after it runs it as an external command, and then creates an image with `ImageIO/read (io/input-stream out)` ([https://github.com/ztellman/rhizome/blob/master/src/rhizome/viz.clj](line 123)). So in `visualize` code, we already have that as `image` ([https://github.com/Engelberg/instaparse/blob/master/src/instaparse/viz.clj](line 88)). We just need a way to return it.

**Comment by Engelberg** [comment]
Yes, it looks like a straightforward change.  Rather than alter the usual behavior of visualize, I'd probably want to make it an additional option to the visualize function, or maybe override one of the existing options like set `:output-file` to `:binary` or something to trigger just returning the image.  Need to think of something that would be clear.  What do you do with the image data when you're not viewing it or saving it to a file?  If I understand the use-case, I might be able to come up with a clearer name.

**Comment by dimitrijer** [comment]
I wanted to encode it to `base64` and then embed it in a JSON response, so I could show it on a web page. Encoding binary data directly into `<img>` elements via Hiccup also occurred to me.

**Comment by arrdem** [comment]
Returning a `byte[]` is probably reasonable to include in instaparse, any particular encoding or transformation beyond that probably doesn't fit IMO as it's gonna be pretty use specific.

**Comment by Engelberg** [comment]
I finally had an opportunity with the long weekend here in the U.S. to revisit some of these issues.  In 1.4.7 I added the ability to call `visualize` with `:output-file :buffered-image` which will cause the function to return a java.awt.image.BufferedImage.  I did this because, as @dimitrijer pointed out, rhizome is already generating a BufferedImage, so that's the most natural thing to return.  One can then call rhizome's save-image or view-image on it, or use java's facilities to turn it into a byte array or a whole bunch of other possible formats.

This was a good addition.  Thanks for the suggestion, and I apologize for the delay.
