### ISSUE TITLE
Some BNF gramars won't parse

### ISSUE THREAD

**Issue by kenrestivo-stem** [Engelberg/instaparse#155]
Just for fun, I tried to see if these would parse:

https://github.com/ronsavage/SQL/blob/master/sql-99.bnf
https://github.com/ronsavage/SQL/blob/master/sql-92.bnf

And they wouldn't. Tried with :ebnf and :abnf. Spent some time chasing that rabbit and realized it would take more time than I had available.

Are those grammars non-standard?

**Comment by arrdem** [comment]
See the **Tutorial** section of the README. Neither of those grammars as-is conform to the recognized BNF variants due to their choice of comment notation and the `<>` naming convention on rules along with the file header and possibly some other things.

It is possible to implement Instaparse support for alternate BNF notations, Instaparse's own BNF interpreter is just a use of instaparse as I recall.

**Comment by kenrestivo-stem** [comment]
Thanks. Not a bug then, closing.
