### ISSUE TITLE
support equivalence check on transform result

### ISSUE THREAD

**Issue by carocad** [Engelberg/instaparse#160]
I have a project called `docopt.clj` where I do several transformations to the parse results of instaparse. On a refactor that I did recently I found out that the result of calling the same function twice on the same input resulted in two different values. 

The problem is that they are not "obviously different" but rather implicitly different. This means that executing the following code would return false:

```clojure
(= (non-terminal (first (insta/parse docopt-parser bar)))
    (non-terminal (first (insta/parse docopt-parser bar))))
```

After checking the internals of instaparse I came to the conclusion that the regexp combinator was the one making the problem. My best guest is that it internally uses some Java instances which test false to the equality test. Though I didnt test that hypothesis, I did run a `clojure.data/diff` on the above result and the regexp part was the only difference reported.

This is not a real bug on my program though and I can definitely live with it but I thought it would be better letting you know about it in case that behavior is not intended.

Hope it helps,

PS: the code for the previous example is here: https://github.com/carocad/docopt.clj/blob/master/src/docopt/core.clj#L46

**Comment by aengelberg** [comment]
The lack of regex equality is indeed annoying. I wrote this [helper function](https://github.com/Engelberg/instaparse/blob/master/test/instaparse/core_test.cljc#L20) to get around it in the unit tests.

The actual parse result that `insta/parse` returns (which is just Clojure data) should have structural equality, but since you've chosen to then transform that data into instaparse combinators, which could contain regexes inside of them, that breaks the guarantee.

Is there a concrete use case (other than test cases) for having parsers and combinators be structurally equal?

**Comment by carocad** [comment]
@aengelberg No, I dont have a use case other than unit test.

I simply decided to report it in case that it might have escaped your sight but it seems like it didnt :)
