### ISSUE TITLE
Is it possible to get the rule name for the :expecting for the :reason on failure?

### ISSUE THREAD

**Issue by danielytics** [Engelberg/instaparse#179]
If I have a parse failure, it would be really useful if I could determine which rules names it was expecting. For example:

```clj
{:index 48,
 :reason
 [{:tag :string, :expecting "\n"}
  {:tag :optional, :expecting :end-of-string}
  {:tag :string, :expecting "#"}
  {:tag :regexp, :expecting #"^\s+"}],
 ...
``` 

I'm trying to output useful error information to the user, but currently the best I can do is to use `pprint-failure` or similar (I use a homemade version that shows the previous few lines as context, and adds line numbers), but showing a list of regular expressions to the end user isn't particularly useful. I'd like to detect which rules were expected (but not matched) and then either output those rule names verbatim, or use them to look up an end-user-friendly message.

Is this currently possible? I wasn't able to find a way myself.

**Comment by Engelberg** [comment]
Try the total parsing mode which embeds the error in the parse tree. That
should give you the context, including the rule where it failed.

On Mar 11, 2018 2:30 PM, "Dan Kersten" <notifications@github.com> wrote:

If I have a parse failure, it would be really useful if I could determine
which rules names it was expecting. For example:

{:index 48,
 :reason
 [{:tag :string, :expecting "\n"}
  {:tag :optional, :expecting :end-of-string}
  {:tag :string, :expecting "#"}
  {:tag :regexp, :expecting #"^\s+"}],
 ...

I'm trying to output useful error information to the user, but currently
the best I can do is to use ``pprint-failure` or similar (I use a homemade
version that shows the previous few lines as context, and adds line
numbers), but showing a list of regular expressions to the end user isn't
particularly useful. I'd like to detect which rules were expected (but not
matched) and then either output those rule names verbatim, or use them as
keys to look up an end-user-friendly message.

Is this currently possible? I wasn't able to find a way myself.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/Engelberg/instaparse/issues/179>, or mute the thread

**Comment by danielytics** [comment]
The problem I'm having with the total parse mode is it doesn't always seem to work for me, in that sometimes it returns just the start rule and nothing else (`[:start-rule]`) and sometimes it returns the start rule and the error with absolutely everything else in the error, even though non-total parse mode says the error is a lot later (`[:start-rule [:instaparse/failure "everything in the file besides the first few tokens"]]`). I've seen this a few times today when the error turned out to be a rule much further down (ie not the start rule).

I'm not really sure why this happens for me, but I've not found total parse mode to be that helpful at least half of the time.

As a concrete example, here's a parse error I'm debugging right now:

Output from normal parse mode:
```clj
{:index 619,
 :reason
 [{:tag :string, :expecting "\n"}
  {:tag :string, :expecting "#"}
  {:tag :regexp, :expecting #"^\s+"}],
 :line 37,
 :column 2,
 :text "««««elif param2 > 5:#«8»"}
```

Total parse mode output:
```clj

Total parse mode results:

[:gdscript
 [:instaparse/failure
  "# a file is a class!#«0»\n\n# inheritance#«0»\n\nextends BaseClass#«0»\n#extends \"../FooClass\"#«0»\n\n# member variables#«0»\n\nvar a = 5#«0»\nvar s = \"Hello\"#«0»\nvar arr = [1, 2, 3]#«0»\nvar dict = {\"key\": \"value\", 2:3}#«0»\n\n# constants#«0»\n\nconst answer = 42#«0»\nconst thename = \"Charly\"#«0»\n\n# enums#«0»\n\nenum {UNIT_NEUTRAL, UNIT_ENEMY, UNIT_ALLY}#«0»\nenum Named {THING_1, THING_2, ANOTHER_THING = -1}#«0»\n\n# built-in vector types#«0»\n\nvar v2 = Vector2(1, 2)#«0»\nvar v3 = Vector3(1, 2, 3)#«0»\n\n# function#«0»\n\nfunc some_function(param1, param2):#«0»\n»»»»var local_var = 5#«0»\n\nif param1 < local_var:#«4»\n»»»»print(param1)#«4»\n««««elif param2 > 5:#«8»\n»»»»print(param2)#«4»\n««««else:#«8»\n»»»»print(\"fail!\")#«4»\n\n««««for i in range(20):#«8»\n»»»»print(i)#«4»\n\n««««while param2 != 0:#«8»\n»»»»param2 -= 1#«4»\n\n««««var local_var2 = param1+3#«8»\nreturn local_var2#«4»\n\n\n««««# inner class#«4»\n\nclass Something:#«0»\n»»»»var a = 10#«0»\n\n««««# constructor#«4»\n\nfunc _init():#«0»\n»»»»print(\"constructed!\")#«0»\nvar lv = Something.new()#«4»\nprint(lv.a)#«4»\n««««#EOF#«4»"]]
```

And pretty printed (this removes the `«` and `»`, which are inserted prior to parsing to track python-style indents):
```
Parse error on line 37, column 10
 35	    if param1 < local_var:
 36	        print(param1)
 37	    elif param2 > 5:
```

The issue is that the previous 36 lines parse fine and if I delete line 37, it parses successfully. 

Presumably its inside some rule that isn't able to completely parse and therefore it and all its parent rules are failing, but the total parse mode output doesn't help in tracking this down at all. For my debugging purposes, I can use trace mode, but for end users that's not very useful.

**Comment by danielytics** [comment]
Thinking about it more today (and investigating trace mode), its possible that the total parse mode only fails when the grammar is bad (ie it can't actually parse because its ill-defined) rather than when the input is bad. If this is the case, then your suggestion of using total parse mode to augment the output to the user should work fine. I'll investigate some  more and if it turns out that this is it, then I'll close this issue. Basically, as long as I can generate useful error messages (even if its a bit of work), then I'm happy :)
