### ISSUE TITLE
Question: Neophyte - Is transform best route for disambiguation?

### ISSUE THREAD

**Issue by FrankC01** [Engelberg/instaparse#91]
Context: Leveraging *instaparse* with this [Manchester OWL Grammar](http://www.w3.org/TR/owl2-manchester-syntax/) and I found it results in ambiguity. To your credit, when using "parses" function, I see that it does consider the right outcome but also to your disclaimer the result may still be ambiguous. 

I found I was butchering the EBNF to create a rule for all productions, ugh and untenable. So, I'm concluding that I could disambiguate in a transform step and wanted to get your perspective. Should I strive to create a smarter grammar? Or, as I mentioned, deal with it post-parse?

**Comment by Engelberg** [comment]
I think it depends on just how bad the ambiguity.  If it is something that is exponential in nature, for example, doubling the number of possible parses as the length of the input grows, clearly that's going to be a problem.  But if you know that parsing always generates 2 or 3 discrete parses (for example, a scenario where the header can or be considered as part of the body or treated separately as a header), then feel free to keep it as-is and deal with it post-parse.

A couple tips:
1. Don't rely on the order in which it shows up in the output of the parses function (e.g., going by the observation "the one I want is always the last"), because I keep hoping to make parallelization improvements to instaparse in which the order of outputs might change.

2. If you're going to totally rewrite the grammar, I'd recommend trying to do it without the ordered choice operator /.  However, the ordered choice operator can be a wonderfully convenient tool for situations like this.  Sometimes, just going through and changing some of the | to / in your grammar is enough to disambiguate (because often grammar writers implicitly assume that the left-most side of the rule will take precedence).

**Comment by FrankC01** [comment]
It is exponential but manageable: i.e. one statement generates 6 possible parses. So, I'm thinking of simplifying 'type' out of the grammar and once I have the parse I can collect qualified types and assert the right clause associated to the type.

**Comment by Engelberg** [comment]
If it works for you to do that, and that's the easiest path to getting something working, by all means, do it.  That's one of the values to handling ambiguity and producing all possible parses; you can inspect it, and decide what you want to do about it.
