### ISSUE TITLE
Express Mozilla DN double bar ||

### ISSUE THREAD

**Issue by siscia** [Engelberg/instaparse#95]
Hi :)

thanks for the wonderful work about instaparse.

I was wonder if it is possible to express somehow the double bars that mozilla uses:

https://developer.mozilla.org/en-US/docs/Web/CSS/Value_definition_syntax#Double_bar

Thanks for your time :)

**Comment by Engelberg** [comment]
In principle, yes, it would definitely be possible for instaparse to handle double bar notation (I've never seen it until just now when you pointed me to it, so I don't know how standard that notation is, but I can see why it makes sense in the context of parsing css).

One way would be for something like

    width || style || color

to turn into something like 

    width (style? color? | color? style?) | style (width? color? | color? width?) | color (width? style? | style? width?)

But this is a factorial explosion of possibilities.  If you had, say, ten possibilities separated by double bars, it would cripple the performance.

I can also imagine ways to implement this more efficiently at the combinator level by coming up with a custom combinator rather than converting it to existing ones.  Still, a lot of potential performance issues to work out.

I think if I wanted to use instaparse right now to do something like this, I would simply write the grammar as:

    (width | style | color) +

and then after a tree has been produced, I would traverse the tree and check that each "double-bar" node had at most one of each alternative.

This would also allow for the benefit of coming up with really clear error messages, because you could say things like, "You specified two styles".  Or you could just issue a warning, and proceed by using the last style given.  The point is you'd have a lot of flexibility and power by just using instaparse to simply do the job of parsing and get the tree into the right shape, and then making a pass over the tree to check that the semantics are correct.

**Comment by siscia** [comment]
Thanks for the time you took, I really appreciate :)

Actually I see exactly the same problem you saw and I opted for the way you suggest.

Thank you :)
